#! /usr/bin/env python
"""
Para correrlo desde la consola, hay que darle permisos de ejecucion
chmod +x CLambda
"""
import sys
from calculoLambda import *

if len(sys.argv) > 2:
  print("El uso correcto es ./CLambda 'input string' o ./CLambda")
  sys.exit()

if len(sys.argv) == 2:
  exp_str = sys.argv[1]
  print(parse(exp_str))

if len(sys.argv) == 1:
  while True:
    try:
      exp_str = raw_input('> ')
      parsed = parse(exp_str)
      # print parsed.printString()
    except EOFError:
      break
    except (UnexpectedTokenException, ExpressionMustBeBool, ExpressionMustBeNat, ExpressionMustBeLambda, ExpressionsMustHaveEqualType, ExpressionMustBeApplicable) as e:
      print(e.message)
      pass

"""
Grammar

S -> Lambda
Lambda -> App
App -> App Final | Final
Final -> 0 | true | false | Var | if Lambda then Lambda else Lambda | succ ( Lambda ) | pred ( Lambda ) | iszero ( Lambda ) | ( Lambda ) | \ Var : Tipo . Lambda
Tipo -> Bool Flecha | Nat Flecha
Flecha -> -> Tipo |
Var -> var
"""
