#! /usr/bin/env python
"""
Para correrlo desde la consola, hay que darle permisos de ejecucion
chmod +x CLambda
"""
import sys
from calculoLambda import parse

if len(sys.argv) > 2:
  print("El uso correcto es ./CLambda 'input string' o ./CLambda")
  sys.exit()

if len(sys.argv) == 2:
  exp_str = sys.argv[1]
  print(parse(exp_str))

if len(sys.argv) == 1:
  while True:
    try:
      exp_str = raw_input('> ')
    except EOFError:
      break
    print(parse(exp_str))

"""
Grammar

S -> E
E -> 0 | B | var | (E) | succ(E) | pred(E) | iszero(E) | if E then E else E | L
B -> true | false
T -> Bool R | Nat R
R -> -> T | LAMBDA
L -> \var:T.E A
A -> E | LAMBDA
"""

"""
Grammar

S -> E.
E -> 0 | B | var | ( E ) | succ ( E ) | pred ( E ) | iszero ( E ) | if E then E else E | L.
B -> true | false.
T -> Bool R | Nat R.
R -> flecha T | .
L -> lambda var : T punto E A.
A -> E | .
"""
